module.exports={
	About: require('./views/About'),
	Admin: require('./views/Admin'),
	AdminHeader: require('./views/AdminHeader'),
	AdminPlus: require('./views/AdminPlus'),
	CSA: require('./views/CSA'),
	Contact: require('./views/Contact'),
	CustomerInfo: require('./views/CustomerInfo'),
	Footer: require('./views/Footer'),
	GetInvolved: require('./views/GetInvolved'),
	Header: require('./views/Header'),
	Home: require('./views/Home'),
	InstanceRow: require('./views/InstanceRow'),
	ManageCustomer: require('./views/ManageCustomer'),
	Markets: require('./views/Markets'),
	Members: require('./views/Members'),
	MyView: require('./views/MyView'),
	OrderOptions: require('./views/OrderOptions'),
	Resource: require('./views/Resource'),
	ResourceRow: require('./views/ResourceRow'),
	Seasons: require('./views/Seasons'),
	Signup: require('./views/Signup'),
	Toast: require('./views/Toast'),
	WeekOptions: require('./views/WeekOptions'),
	modal: require('./views/modal')
}